/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.69
 * Generated at: 2024-06-18 16:06:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write(" function getOtp()\r\n");
      out.write(" {\r\n");
      out.write("\tvar mob= document.getElementById(\"mob\").value;\r\n");
      out.write("\t\r\n");
      out.write("\tvar xmlhttp;\r\n");
      out.write("\tif (window.XMLHttpRequest)\r\n");
      out.write("\t{\r\n");
      out.write("\t// code for IE7+, Firefox, Chrome, Opera, Safari\r\n");
      out.write("\t     xmlhttp=new XMLHttpRequest();\r\n");
      out.write("\t}\r\n");
      out.write("\telse\r\n");
      out.write("\t{// code for IE6, IE5\r\n");
      out.write("\t xmlhttp=new ActiveXObject(\"Microsoft.XMLHTTP\");\r\n");
      out.write("\t }\r\n");
      out.write("\t \r\n");
      out.write("\t \r\n");
      out.write("\txmlhttp.onreadystatechange=function()\r\n");
      out.write("\t{\r\n");
      out.write("\tif (xmlhttp.status==200)\r\n");
      out.write("\t{\r\n");
      out.write("\t//document.getElementById(\"fname\").value\r\n");
      out.write("\r\n");
      out.write("\t    document.getElementById(\"t\").value=xmlhttp.responseText;\r\n");
      out.write("\t    document.getElementById(\"tt\").innerHTML=xmlhttp.responseText;\r\n");
      out.write("\t   \r\n");
      out.write("\t}\r\n");
      out.write("\t \r\n");
      out.write("\t}\r\n");
      out.write("\t \r\n");
      out.write("\t xmlhttp.open(\"GET\",\"LoginOtpServlet?mob=\"+mob,true);\r\n");
      out.write("\txmlhttp.send(); \r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write(" }\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<form action=\"LoginServlet\" method=\"post\">\r\n");
      out.write("<table border=\"3\" bgcolor=\"yellow\">\r\n");
      out.write("<tr><td>UID</td><td><input type=\"text\" name=\"uid\"></td></tr>\r\n");
      out.write("<tr><td>Pass</td><td><input type=\"password\" name=\"pass\"></td></tr>\r\n");
      out.write("\r\n");
      out.write("<tr><td>Mobile</td><td><input type=\"text\" name=\"mob\" id=\"mob\" onblur=\"getOtp()\">\r\n");
      out.write("\r\n");
      out.write("<input type=\"hidden\" name=\"otp\" readonly=\"readonly\" id=\"t\" size=\"6\">\r\n");
      out.write("</td>\r\n");
      out.write("\r\n");
      out.write("</tr>\r\n");
      out.write("<tr><td><input type=\"submit\" value=\"Login\">\r\n");
      out.write("\r\n");
      out.write("</td><td><p id=\"tt\"></p></td></tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
